Repository josh-flatt/OneCard, pull requests merged in 2024-04, with the labels that each got.

#36 Username bugfix
  app/OneCard.client/src/app/create-user-profile/create-user-profile.component.html
  app/OneCard.client/src/app/create-user-profile/create-user-profile.component.ts
  app/OneCard.client/src/app/edit-user-profile/edit-user-profile.component.html
  app/OneCard.client/src/app/my-profile/my-profile.component.html
  app/OneCard.client/src/app/my-profile/my-profile.component.ts
  app/OneCard.server/.vs/OneCard.server/DesignTimeBuild/.dtbcache.v2
  app/OneCard.server/.vs/OneCard.server/FileContentIndex/0248d993-fc99-472b-82ee-016168c35f79.vsidx
  app/OneCard.server/.vs/OneCard.server/FileContentIndex/0ef81adf-c0a4-4355-9f37-6253e8b78933.vsidx
  app/OneCard.server/.vs/OneCard.server/FileContentIndex/3dd99a54-efa8-414c-abf4-dddc4233a484.vsidx
  app/OneCard.server/.vs/OneCard.server/FileContentIndex/4db24113-5888-4301-a357-292a52ac7b6d.vsidx
  app/OneCard.server/.vs/OneCard.server/FileContentIndex/6448e9eb-4dee-42cb-9012-9f5612387249.vsidx
  app/OneCard.server/.vs/OneCard.server/FileContentIndex/7ff1304f-4961-4fbc-b088-266841c0d927.vsidx
  app/OneCard.server/.vs/OneCard.server/v17/.futdcache.v2
  app/OneCard.server/.vs/OneCard.server/v17/.suo
  app/OneCard.server/.vs/ProjectEvaluation/onecard.server.metadata.v7.bin
  app/OneCard.server/.vs/ProjectEvaluation/onecard.server.projects.v7.bin
  app/OneCard.server/bin/Debug/net8.0/OneCard.server.dll
  app/OneCard.server/bin/Debug/net8.0/OneCard.server.exe
  app/OneCard.server/bin/Debug/net8.0/OneCard.server.pdb
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.AssemblyInfo.cs
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.AssemblyInfoInputs.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.assets.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.csproj.AssemblyReference.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.csproj.CopyComplete
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.csproj.CoreCompileInputs.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.dll
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.genruntimeconfig.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.pdb
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.sourcelink.json
  app/OneCard.server/obj/Debug/net8.0/apphost.exe
  app/OneCard.server/obj/Debug/net8.0/ref/OneCard.server.dll
  app/OneCard.server/obj/Debug/net8.0/refint/OneCard.server.dll
  app/OneCard.server/obj/OneCard.server.csproj.nuget.dgspec.json
  app/OneCard.server/obj/OneCard.server.csproj.nuget.g.props
  app/OneCard.server/obj/project.assets.json
  app/OneCard.server/obj/project.nuget.cache
Labels: bug

#37 Merging Abby's branch
  .gitignore
  app/OneCard.client/src/app/services/auth/auth.service.spec.ts
  app/OneCard.client/src/app/services/auth/auth.service.ts
  app/scripts/build.sh
  docs/abby.dox
Labels: enhancement

#38 documentation
  docs/Documentation/Back-End Specifics.docx
  docs/Documentation/Laser Engraver Basics & Physical Card Details.docx
  docs/Documentation/Lasercutting Guide.pdf
  docs/Documentation/OneCard FAQ.txt
  docs/Documentation/purchases.xlsx
Labels: documentation

#39 Changed a couple of things regarding abby's merge.
  app/OneCard.client/src/app/my-profile/my-profile.component.css
  app/OneCard.client/src/app/my-profile/my-profile.component.html
  app/OneCard.client/src/app/services/auth/auth.service.spec.ts
  app/OneCard.client/src/app/services/auth/auth.service.ts
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.AssemblyInfo.cs
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.AssemblyInfoInputs.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.assets.cache
  app/OneCard.server/obj/OneCard.server.csproj.nuget.dgspec.json
  app/OneCard.server/obj/OneCard.server.csproj.nuget.g.props
  app/OneCard.server/obj/project.assets.json
  app/OneCard.server/obj/project.nuget.cache
  docs/abby.dox
Labels: enhancement

#40 fixed issue updating and displaying profile picture
  app/OneCard.client/src/app/create-user-profile/create-user-profile.component.html
  app/OneCard.client/src/app/edit-user-profile/edit-user-profile.component.html
  app/OneCard.client/src/app/user-profile/user-profile.component.html
  app/OneCard.client/src/environments/environment.ts
  app/OneCard.server/.vs/OneCard.server/DesignTimeBuild/.dtbcache.v2
  app/OneCard.server/.vs/OneCard.server/FileContentIndex/6448e9eb-4dee-42cb-9012-9f5612387249.vsidx
  app/OneCard.server/.vs/OneCard.server/v17/.futdcache.v2
  app/OneCard.server/.vs/OneCard.server/v17/.suo
  app/OneCard.server/.vs/ProjectEvaluation/onecard.server.metadata.v7.bin
  app/OneCard.server/.vs/ProjectEvaluation/onecard.server.projects.v7.bin
  app/OneCard.server/Controllers/CardUserController.cs
  app/OneCard.server/appsettings.Development.json
  app/OneCard.server/appsettings.json
  app/OneCard.server/bin/Debug/net8.0/OneCard.server.dll
  app/OneCard.server/bin/Debug/net8.0/OneCard.server.exe
  app/OneCard.server/bin/Debug/net8.0/OneCard.server.pdb
  app/OneCard.server/bin/Debug/net8.0/appsettings.Development.json
  app/OneCard.server/bin/Debug/net8.0/appsettings.json
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.AssemblyInfo.cs
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.AssemblyInfoInputs.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.GeneratedMSBuildEditorConfig.editorconfig
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.assets.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.csproj.AssemblyReference.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.csproj.CoreCompileInputs.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.dll
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.genruntimeconfig.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.pdb
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.sourcelink.json
  app/OneCard.server/obj/Debug/net8.0/apphost.exe
  app/OneCard.server/obj/Debug/net8.0/ref/OneCard.server.dll
  app/OneCard.server/obj/Debug/net8.0/refint/OneCard.server.dll
  app/OneCard.server/obj/OneCard.server.csproj.nuget.dgspec.json
  app/OneCard.server/obj/OneCard.server.csproj.nuget.g.props
  app/OneCard.server/obj/project.assets.json
  app/OneCard.server/obj/project.nuget.cache
Labels: bug

#41 Removal of test views/models
  app/OneCard.client/src/app/app.routes.ts
  app/OneCard.client/src/app/edit-hero/edit-hero.component.css
  app/OneCard.client/src/app/edit-hero/edit-hero.component.html
  app/OneCard.client/src/app/edit-hero/edit-hero.component.ts
  app/OneCard.client/src/app/models/super-hero.ts
  app/OneCard.client/src/app/services/super-hero.service.ts
  app/OneCard.client/src/app/super-hero/super-hero.component.css
  app/OneCard.client/src/app/super-hero/super-hero.component.html
  app/OneCard.client/src/app/super-hero/super-hero.component.spec.ts
  app/OneCard.client/src/app/super-hero/super-hero.component.ts
  app/OneCard.client/src/environments/environment.ts
  app/OneCard.server/.vs/OneCard.server/DesignTimeBuild/.dtbcache.v2
  app/OneCard.server/.vs/OneCard.server/v17/.futdcache.v2
  app/OneCard.server/.vs/OneCard.server/v17/.suo
  app/OneCard.server/.vs/ProjectEvaluation/onecard.server.metadata.v7.bin
  app/OneCard.server/.vs/ProjectEvaluation/onecard.server.projects.v7.bin
  app/OneCard.server/Controllers/SuperHeroController.cs
  app/OneCard.server/Data/DataContext.cs
  app/OneCard.server/Models/SuperHero.cs
  app/OneCard.server/Program.cs
  app/OneCard.server/bin/Debug/net8.0/OneCard.server.dll
  app/OneCard.server/bin/Debug/net8.0/OneCard.server.exe
  app/OneCard.server/bin/Debug/net8.0/OneCard.server.pdb
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.AssemblyInfo.cs
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.AssemblyInfoInputs.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.csproj.AssemblyReference.cache
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.csproj.FileListAbsolute.txt
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.dll
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.pdb
  app/OneCard.server/obj/Debug/net8.0/OneCard.server.sourcelink.json
  app/OneCard.server/obj/Debug/net8.0/apphost.exe
  app/OneCard.server/obj/Debug/net8.0/ref/OneCard.server.dll
  app/OneCard.server/obj/Debug/net8.0/refint/OneCard.server.dll
Labels: enhancement
